name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

env:
  FORCE_COLOR: "1"

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          release: nightly
      - name: Report
        run: odin report
      - name: Run client example
        run: odin run examples/client
        timeout-minutes: 1
      - name: Odin check
        if: success() || failure()
        shell: bash
        run: for e in examples/*/; do odin check "$e" -vet --strict-style || exit 1; done
        timeout-minutes: 2
      - name: Unit tests
        if: success() || failure()
        run: odin test tests/unit -vet --strict-style
        timeout-minutes: 5
      - name: Parser fuzzing
        if: success() || failure()
        run: odin test tests/fuzz -o:speed -define:FUZZ_ITERATIONS=2000000
        timeout-minutes: 10
      - name: Server tests
        if: success() || failure()
        run: odin test tests/server -vet --strict-style
        timeout-minutes: 10
      - name: Server tests (address sanitizer)
        if: (success() || failure()) && runner.os == 'Linux'
        run: odin test tests/server -sanitize:address -debug
        timeout-minutes: 10
